const STORAGE_KEY = 'my-rhythm-planner-v1';
const monthNames = ['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'];
const weekDays = ['Воскресенье','Понедельник','Вторник','Среда','Четверг','Пятница','Суббота'];
const state = loadState();
let viewDate = new Date();
let selectedDate = dateKey(new Date());

const $ = (id) => document.getElementById(id);
function loadState(){ try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || {tasks:[],notes:[]}; } catch { return {tasks:[],notes:[]}; } }
function save(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function dateKey(date){ return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`; }
function parseDate(key){ const [y,m,d]=key.split('-').map(Number); return new Date(y,m-1,d); }
function escapeHTML(value=''){ return String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function tasksFor(key){ return state.tasks.filter(t=>t.date===key).sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99')); }
function loadLevel(count){ return count>=7?'red':count>=4?'yellow':'green'; }
function render(){ renderCalendar(); renderNotes(); }
function renderCalendar(){
  $('monthTitle').textContent = `${monthNames[viewDate.getMonth()]} ${viewDate.getFullYear()}`;
  const first = new Date(viewDate.getFullYear(),viewDate.getMonth(),1); const offset=(first.getDay()+6)%7; const days=new Date(viewDate.getFullYear(),viewDate.getMonth()+1,0).getDate();
  const grid=$('calendarGrid'); grid.innerHTML='';
  for(let i=0;i<offset;i++) grid.appendChild(dayCard(new Date(viewDate.getFullYear(),viewDate.getMonth(),i-offset+1),true));
  for(let day=1;day<=days;day++) grid.appendChild(dayCard(new Date(viewDate.getFullYear(),viewDate.getMonth(),day),false));
  while(grid.children.length%7) grid.appendChild(dayCard(new Date(viewDate.getFullYear(),viewDate.getMonth()+1,grid.children.length-offset-days+1),true));
}
function dayCard(date,outside){
  const key=dateKey(date), tasks=tasksFor(key), level=loadLevel(tasks.length), card=document.createElement('article'); card.className=`calendar-day ${outside?'outside ':''}${key===dateKey(new Date())?'today':''}`; card.tabIndex=0; card.setAttribute('aria-label',`${weekDays[date.getDay()]}, ${date.getDate()} ${monthNames[date.getMonth()]}. ${tasks.length} дел. ${level==='green'?'Спокойная':level==='yellow'?'Средняя':'Высокая'} загруженность.`);
  const visible=tasks.slice(0,3); card.innerHTML=`<div class="day-head"><span class="day-number">${date.getDate()}</span><span title="${tasks.length} дел"><i class="traffic-dot ${level}"></i><span class="day-load"> ${tasks.length} ${tasks.length===1?'дело':'дел'}</span></span></div>${visible.map(t=>`<span class="mini-task ${t.done?'done':''}">${t.time?escapeHTML(t.time)+' · ':''}${escapeHTML(t.title)}</span>`).join('')}${tasks.length>3?`<span class="more-tasks">ещё ${tasks.length-3}</span>`:''}`;
  card.addEventListener('click',()=>openDay(key)); card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')openDay(key)}); return card;
}
function renderNotes(){ const list=$('notesList'); $('notesCount').textContent=state.notes.filter(n=>!n.done).length; list.innerHTML=''; if(!state.notes.length){list.innerHTML='<div class="empty-state">Здесь появятся дела без даты.</div>';return;} state.notes.forEach(note=>{ const row=document.createElement('div'); row.className='note-item'; row.innerHTML=`<input type="checkbox" ${note.done?'checked':''} aria-label="Отметить заметку выполненной"><span class="note-text ${note.done?'done':''}">${escapeHTML(note.text)}</span><button class="delete-note" aria-label="Удалить заметку">×</button>`; row.querySelector('input').addEventListener('change',()=>{note.done=!note.done;save();renderNotes()}); row.querySelector('.delete-note').addEventListener('click',()=>{state.notes=state.notes.filter(n=>n.id!==note.id);save();renderNotes()}); list.appendChild(row); }); }
function openModal(id){$(id).classList.remove('hidden')}; function closeModal(id){$(id).classList.add('hidden')}
function openDay(key){ selectedDate=key; const d=parseDate(key), tasks=tasksFor(key); $('dayModalTitle').textContent=`${d.getDate()} ${monthNames[d.getMonth()]} · ${tasks.length} ${tasks.length===1?'дело':'дел'}`; const list=$('dayTaskList'); list.innerHTML=tasks.length?'':'<div class="empty-state">На этот день задач нет. Можно выдохнуть или добавить новую.</div>'; tasks.forEach(task=>{const row=document.createElement('div');row.className='day-task';row.innerHTML=`<input type="checkbox" ${task.done?'checked':''} aria-label="Выполнено"><div class="task-main"><div class="task-title ${task.done?'done':''}">${escapeHTML(task.title)}</div><div class="task-meta"><span class="category">${escapeHTML(task.category)}</span>${task.time?`<span>${escapeHTML(task.time)}</span>`:''}</div>${task.description?`<div class="task-meta">${escapeHTML(task.description)}</div>`:''}</div><div class="task-actions"><button class="small-action edit">Изм.</button><button class="small-action delete">Удал.</button></div>`; row.querySelector('input').addEventListener('change',()=>{task.done=!task.done;save();render();openDay(key)});row.querySelector('.edit').addEventListener('click',()=>openTaskForm(task));row.querySelector('.delete').addEventListener('click',()=>{if(confirm('Удалить эту задачу?')){state.tasks=state.tasks.filter(t=>t.id!==task.id);save();render();openDay(key)}});list.appendChild(row)}); openModal('dayModal'); }
function openTaskForm(task=null,date=selectedDate){ $('taskModalTitle').textContent=task?'Редактировать задачу':'Новая задача'; $('taskId').value=task?.id||''; $('taskTitle').value=task?.title||''; $('taskDate').value=task?.date||date; $('taskTime').value=task?.time||''; $('taskCategory').value=task?.category||'Работа'; $('taskDescription').value=task?.description||''; closeModal('dayModal');openModal('taskModal');setTimeout(()=>$('taskTitle').focus(),50); }
$('previousMonth').onclick=()=>{viewDate.setMonth(viewDate.getMonth()-1);renderCalendar()}; $('nextMonth').onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);renderCalendar()}; $('todayButton').onclick=()=>{viewDate=new Date();renderCalendar()}; $('addTaskButton').onclick=()=>openTaskForm(null,dateKey(new Date())); $('addDayTaskButton').onclick=()=>openTaskForm(null,selectedDate);
$('taskForm').addEventListener('submit',e=>{e.preventDefault(); const id=$('taskId').value; const data={id:id||crypto.randomUUID(),title:$('taskTitle').value.trim(),date:$('taskDate').value,time:$('taskTime').value,category:$('taskCategory').value,description:$('taskDescription').value.trim(),done:false}; if(!data.title||!data.date)return; const old=state.tasks.find(t=>t.id===id); if(old){data.done=old.done;Object.assign(old,data)}else state.tasks.push(data); save(); viewDate=parseDate(data.date); selectedDate=data.date; closeModal('taskModal');render();openDay(data.date); });
$('noteForm').addEventListener('submit',e=>{e.preventDefault();const text=$('noteInput').value.trim();if(!text)return;state.notes.unshift({id:crypto.randomUUID(),text,done:false});save();$('noteInput').value='';renderNotes()});
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close))); document.querySelectorAll('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)})); document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal-backdrop:not(.hidden)').forEach(m=>closeModal(m.id))}); render();
