(() => {
  'use strict';
  const STORAGE_KEY='my-rhythm-planner-v2';
  const LEGACY_KEY='my-rhythm-planner-v1';
  const BACKUP_KEY='my-rhythm-planner-local-backup-v2';
  const cfg=window.PLANNER_CONFIG||{};
  const remote=Boolean(cfg.supabaseUrl&&cfg.supabasePublishableKey);
  const state={items:[]};
  const $=id=>document.getElementById(id);
  const monthNames=['январь','февраль','март','апрель','май','июнь','июль','август','сентябрь','октябрь','ноябрь','декабрь'];
  const weekdayNames=['воскресенье','понедельник','вторник','среда','четверг','пятница','суббота'];
  const weekdayShort=['Вс','Пн','Вт','Ср','Чт','Пт','Сб'];
  const categoryNames=['Работа','Личные дела','Спорт','Иное'];
  let view='week', viewDate=new Date(), selectedDate=keyOf(new Date()), activeDay=null, editing=null, busy=false, pendingPersist=false, pollTimer=null, savingTask=false;
  const removedIds=new Set(), dirtyIds=new Set();
  const clone=x=>JSON.parse(JSON.stringify(x));
  function uid(){return crypto.randomUUID?crypto.randomUUID():`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`}
  function keyOf(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
  function fromKey(k){const [y,m,d]=k.split('-').map(Number);return new Date(y,m-1,d,12)}
  function shift(k,n){const d=fromKey(k);d.setDate(d.getDate()+n);return keyOf(d)}
  function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function item(id){return state.items.find(x=>x.id===id)}
  function upsert(id,kind,data){removedIds.delete(id);dirtyIds.add(id);const row={id,kind,data:clone(data)};const i=state.items.findIndex(x=>x.id===id);if(i<0)state.items.push(row);else state.items[i]=row}
  function remove(id){state.items=state.items.filter(x=>x.id!==id);dirtyIds.delete(id);removedIds.add(id)}
  function localLoad(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY));state.items=Array.isArray(v?.items)?v.items:[]}catch{state.items=[]}}
  function status(text,cls=''){const el=$('syncStatus');el.textContent=text;el.className=`sync-status ${cls}`}
  function errorBanner(msg){const box=$('connectionError');box.replaceChildren();if(msg){box.append(document.createTextNode(msg));if(remote){const retry=document.createElement('button');retry.type='button';retry.className='small-action';retry.textContent='Повторить';retry.style.marginLeft='10px';retry.addEventListener('click',async()=>{try{if(dirtyIds.size||removedIds.size)await persist();else{status('Обновляем…','loading');await loadRemote();errorBanner('');status('Общий календарь синхронизирован');render()}}catch(e){errorBanner(`Повторить не удалось. ${String(e.message||e).slice(0,120)}`)}});box.append(retry)}}box.classList.toggle('hidden',!msg);status(remote?'Нет синхронизации':'Локально',remote?'error':'')}
  function apiUrl(path=''){return `${cfg.supabaseUrl.replace(/\/$/,'')}/rest/v1/planner_items${path}`}
  async function api(path,options={}){const res=await fetch(apiUrl(path),{...options,headers:{apikey:cfg.supabasePublishableKey,Authorization:`Bearer ${cfg.supabasePublishableKey}`,'Content-Type':'application/json',...(options.headers||{})}});if(!res.ok)throw new Error(`${res.status} ${await res.text()}`);const body=await res.text();return body?JSON.parse(body):null}
  async function loadRemote(saveCache=true){const rows=[];for(let from=0;;from+=1000){const page=await api('?select=id,kind,data&order=id.asc',{headers:{Range:`${from}-${from+999}`}})||[];rows.push(...page);if(page.length<1000)break}state.items=rows.map(r=>({id:r.id,kind:r.kind,data:r.data}));removedIds.clear();dirtyIds.clear();if(saveCache)localStorage.setItem(STORAGE_KEY,JSON.stringify({items:state.items}));}
  function backupObject(items=state.items){return {format:'my-rhythm-planner-backup',version:2,exportedAt:new Date().toISOString(),items:clone(items)}}
  function downloadBackup(items=state.items){if(!items.length){alert('В календаре пока нет записей для копирования.');return}const blob=new Blob([JSON.stringify(backupObject(items),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`moj-ritm-backup-${keyOf(new Date())}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function parseBackup(text){const value=JSON.parse(text);if(!value||value.format!=='my-rhythm-planner-backup'||value.version!==2||!Array.isArray(value.items))throw new Error('Это не копия планера версии 2.');const allowed=new Set(['task','habit','habit_check','override','reminder','note','shopping']),seen=new Set();for(const row of value.items){if(!row||typeof row.id!=='string'||!allowed.has(row.kind)||!row.data||typeof row.data!=='object'||Array.isArray(row.data)||seen.has(row.id))throw new Error('Файл копии повреждён или содержит неподдерживаемые записи.');seen.add(row.id)}return value.items}
  function importSummary(items){const labels={task:'Задачи',habit:'Привычки',habit_check:'Отметки привычек',override:'Изменения повторов',reminder:'Напоминания',note:'Заметки',shopping:'Покупки'},counts={};for(const row of items)counts[row.kind]=(counts[row.kind]||0)+1;return Object.entries(counts).map(([kind,count])=>`${labels[kind]}: ${count}`).join(' · ')}
  function showImportCandidate(items,source){cloudImportCandidate=items;const summary=$('cloudImportSummary'),preview=$('cloudImportPreview'),confirmButton=$('cloudImportConfirm');summary.textContent=items.length?`${source}: ${importSummary(items)}. Записи станут общими для всех, кто откроет ссылку.`:'Выбранная копия пуста.';preview.textContent=items.slice(0,12).map(row=>{const d=row.data||{};return `${row.kind==='task'?(d.date||'')+' '+(d.time||'')+' ':''}${d.title||d.text||row.kind}`}).join('\n');preview.classList.toggle('hidden',!items.length);confirmButton.disabled=!items.length;}
  let cloudImportCandidate=[];
  async function openCloudImport(localItems){const modal=$('cloudImportModal'),error=$('cloudImportError'),file=$('cloudImportFile'),confirmButton=$('cloudImportConfirm'),skipButton=$('cloudImportSkip'),marker=`my-rhythm-planner-cloud-import-v2:${encodeURIComponent(cfg.supabaseUrl)}`;showImportCandidate(localItems,localItems.length?'На этом устройстве':'');error.classList.add('hidden');file.value='';modal.classList.remove('hidden');return new Promise(resolve=>{let settled=false;const finish=value=>{if(settled)return;settled=true;modal.classList.add('hidden');file.onchange=null;confirmButton.onclick=null;skipButton.onclick=null;resolve(value)};skipButton.onclick=()=>{sessionStorage.setItem(`${marker}:later`,'yes');finish(false)};file.onchange=async()=>{const selected=file.files?.[0];if(!selected)return;try{const items=parseBackup(await selected.text());showImportCandidate(items,`Файл «${selected.name}»`);error.classList.add('hidden')}catch(e){cloudImportCandidate=[];confirmButton.disabled=true;error.textContent=e.message||'Не удалось прочитать копию.';error.classList.remove('hidden')}};confirmButton.onclick=async()=>{if(!cloudImportCandidate.length)return;confirmButton.disabled=true;error.classList.add('hidden');try{await loadRemote(false);if(state.items.length){error.textContent='В общей базе уже появились записи. Импорт остановлен, чтобы не создать дубли. Резервная копия не удалена.';error.classList.remove('hidden');confirmButton.disabled=false;return}state.items=clone(cloudImportCandidate);removedIds.clear();for(const row of state.items)dirtyIds.add(row.id);await persist();if(dirtyIds.size){error.textContent='Не удалось подтвердить перенос. Копия сохранена; проверьте подключение и нажмите перенос ещё раз.';error.classList.remove('hidden');confirmButton.disabled=false;return}localStorage.setItem(marker,'done');finish(true)}catch(e){error.textContent=`Перенос не завершён: ${String(e.message||e).slice(0,180)}`;error.classList.remove('hidden');confirmButton.disabled=false}}})}
  async function persist(){if(busy){pendingPersist=true;return}busy=true;status('Сохраняем…','loading');try{if(remote){for(const id of removedIds)await api(`?id=eq.${encodeURIComponent(id)}`,{method:'DELETE'});removedIds.clear();const payload=state.items.filter(x=>dirtyIds.has(x.id)).map(x=>({id:x.id,kind:x.kind,data:x.data}));if(payload.length)await api('?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(payload)});dirtyIds.clear();localStorage.setItem(STORAGE_KEY,JSON.stringify({items:state.items}));errorBanner('');status('Общий календарь синхронизирован')}else{dirtyIds.clear();removedIds.clear();localStorage.setItem(STORAGE_KEY,JSON.stringify({items:state.items}));status('Сохранено на этом устройстве')}render();if(activeDay)renderDay(activeDay)}catch(e){console.error(e);errorBanner(`Не удалось подтвердить сохранение. Проверьте подключение к интернету и настройки базы. Ошибка: ${String(e.message||e).slice(0,180)}`)}finally{busy=false;if(pendingPersist){pendingPersist=false;await persist()}}}
  async function deleteRemote(id){remove(id);await persist()}
  function taskRows(){return state.items.filter(x=>x.kind==='task')}
  function overrideRows(taskId,date){return state.items.find(x=>x.kind==='override'&&x.data.taskId===taskId&&x.data.date===date)}
  function instanceFor(task,date,targetDate=date){let o=overrideRows(task.id,date),data={...task.data};if(o?.data.cancelled)return null;if(o?.data.fields)data={...data,...o.data.fields};const key=o?.data.fields?.date||date;if(key!==targetDate)return null;return {...data,id:task.id,taskId:task.id,date:targetDate,series:Boolean(task.data.repeat?.type&&task.data.repeat.type!=='none'),done:o?.data.done??false}}
  function matchesRepeat(data,date){if(date<data.date||(data.endDate&&date>data.endDate))return false;const r=data.repeat||{type:'none'};if(r.type==='none')return date===data.date;const d=fromKey(date),start=fromKey(data.date);if(d<start)return false;if(r.type==='weekly')return (r.days||[]).includes(d.getDay());if(r.type==='monthly-date')return d.getDate()===Number(r.day);if(r.type==='monthly-weekday'){if(d.getDay()!==Number(r.weekday))return false;const ordinal=Math.floor((d.getDate()-1)/7)+1;if(Number(r.ordinal)===-1){const next=new Date(d);next.setDate(d.getDate()+7);return next.getMonth()!==d.getMonth()}return ordinal===Number(r.ordinal)}return date===data.date}
  function allInstances(date){const map=new Map();for(const t of taskRows()){const s=t.data;if(matchesRepeat(s,date)){const x=instanceFor(t,date,date);if(x)map.set(t.id,x)}}for(const o of state.items.filter(x=>x.kind==='override'&&x.data.fields?.date===date)){const t=item(o.data.taskId);if(t){const x=instanceFor(t,o.data.date,date);if(x)map.set(t.id,x)}}return [...map.values()].sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'))}
  function habits(){return state.items.filter(x=>x.kind==='habit').sort((a,b)=>a.data.title.localeCompare(b.data.title,'ru'))}
  function habitDone(id,date){return Boolean(item(`habit-check:${id}:${date}`))}
  function remindersFor(date){const result=[];for(const t of taskRows()){const s=t.data;if(!s.repeat||s.repeat.type==='none'||s.reminderLead==null)continue;const lead=Number(s.reminderLead),occurrence=shift(date,lead);if(matchesRepeat(s,occurrence)){const instance=instanceFor(t,occurrence);if(instance)result.push({id:`reminder:${t.id}:${occurrence}`,taskId:t.id,eventDate:occurrence,text:s.reminderText||s.title})}}return result}
  function dateLabel(k,opts={weekday:'long',day:'numeric',month:'long'}){return new Intl.DateTimeFormat('ru-RU',opts).format(fromKey(k))}
  function dayTasksCount(k){return allInstances(k).length}
  function level(n){return n>=5?'red':n>=3?'yellow':'green'}
  function loadText(n){return n>=5?'очень занят':n>=3?'средняя нагрузка':'спокойно'}
  function habitToggleMarkup(h,k,compact=false){const checked=habitDone(h.id,k);return `<label class="habit-check" data-stop><input type="checkbox" data-habit="${escapeHtml(h.id)}" data-date="${k}" ${checked?'checked':''}><span>${escapeHtml(h.data.title)}</span></label>`}
  function render(){renderCalendar();renderLists();$('publicNoteText').textContent=remote?'Один общий календарь: посетители ссылки видят и могут менять записи.':'Локальный режим: записи сохраняются только в этом браузере.';}
  function renderCalendar(){const box=$('calendarContent');if(view==='week'){const thisMonday=fromKey(keyOf(viewDate));thisMonday.setDate(thisMonday.getDate()-((thisMonday.getDay()+6)%7));const start=keyOf(thisMonday);const end=shift(start,6);$('periodTitle').textContent=`${dateLabel(start,{day:'numeric',month:'short'})} — ${dateLabel(end,{day:'numeric',month:'short',year:'numeric'})}`;box.innerHTML='<div class="week-list" id="weekList"></div>';const list=$('weekList');for(let i=0;i<7;i++)list.append(dayCard(shift(start,i)));}else{const y=viewDate.getFullYear(),m=viewDate.getMonth(),first=new Date(y,m,1,12),offset=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate();$('periodTitle').textContent=`${monthNames[m]} ${y}`;let html=weekdayShort.slice(1).concat(weekdayShort[0]).map(x=>`<div class="month-weekday">${x}</div>`).join('');for(let i=0;i<offset;i++){const d=new Date(y,m,1-offset+i,12);html+=monthDay(keyOf(d),true)}for(let day=1;day<=days;day++)html+=monthDay(keyOf(new Date(y,m,day,12)),false);while((offset+days)%7){const n=(7-(offset+days)%7);for(let i=1;i<=n;i++)html+=monthDay(keyOf(new Date(y,m,days+i,12)),true);break}$('calendarContent').innerHTML=`<div class="month-grid">${html}</div>`;}}
  function dayCard(k){const d=fromKey(k),tasks=allInstances(k),lvl=level(tasks.length),today=k===keyOf(new Date()),hs=habits(),rem=remindersFor(k);const preview=tasks.slice(0,3).map(t=>`<div class="event-preview ${t.done?'done':''}"><span class="event-time">${t.time?escapeHtml(t.time):'—'}</span><span class="event-preview-title">${escapeHtml(t.title)}</span></div>`).join('');const habitHtml=hs.length?`<div class="habit-quick">${hs.map(h=>habitToggleMarkup(h,k,true)).join('')}</div>`:'';const reminderHtml=rem.length?`<div class="reminder-pip">${rem.length} напоминани${rem.length===1?'е':'я'}: ${escapeHtml(rem[0].text)}${rem.length>1?` и ещё ${rem.length-1}`:''}</div>`:'';const card=document.createElement('article');card.tabIndex=0;card.className=`week-card ${today?'today':''}`;card.setAttribute('aria-label',`${dateLabel(k)}. ${tasks.length} задач. ${loadText(tasks.length)}`);card.innerHTML=`<div class="day-top"><div class="day-heading"><span class="day-name">${escapeHtml(weekdayNames[d.getDay()])}</span><span class="day-date">${d.getDate()} ${monthNames[d.getMonth()].slice(0,3)}</span></div><span class="day-load" aria-hidden="true"><i class="traffic-dot ${lvl}"></i></span></div>${preview||(!hs.length&&!rem.length?'<div class="event-preview"><span class="event-preview-title muted">Пока свободно</span></div>':'')}${tasks.length>3?`<div class="more-link">ещё ${tasks.length-3} · открыть день</div>`:''}${habitHtml}${reminderHtml}`;card.addEventListener('click',e=>{if(e.target.closest('[data-stop]'))return;openDay(k)});card.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target===card){e.preventDefault();openDay(k)}});card.querySelectorAll('[data-habit]').forEach(input=>input.addEventListener('change',async e=>{const id=`habit-check:${e.target.dataset.habit}:${e.target.dataset.date}`;if(e.target.checked)upsert(id,'habit_check',{habitId:e.target.dataset.habit,date:e.target.dataset.date});else remove(id);await persist()}));return card}
  function monthDay(k,outside){const d=fromKey(k),n=dayTasksCount(k),lv=level(n),today=k===keyOf(new Date()),parts=dateLabel(k,{day:'numeric',month:'long'});return `<div class="month-day ${outside?'outside':''} ${today?'today':''} ${k===selectedDate?'selected':''}"><button type="button" data-month-day="${k}" aria-label="${escapeHtml(parts)}, ${n} задач"><span>${d.getDate()}</span><span class="month-load"><i class="traffic-dot ${lv}"></i></span></button></div>`}
  function renderLists(){const notes=state.items.filter(x=>x.kind==='note').sort((a,b)=>(a.data.created||'').localeCompare(b.data.created||''));const shops=state.items.filter(x=>x.kind==='shopping').sort((a,b)=>(a.data.created||'').localeCompare(b.data.created||''));const hs=habits();$('notesCount').textContent=notes.filter(x=>!x.data.done).length;$('shoppingCount').textContent=shops.filter(x=>!x.data.done).length;$('habitsCount').textContent=hs.length;$('notesList').innerHTML=notes.length?notes.map(x=>itemMarkup(x,'note')).join(''):'<div class="empty-state">Здесь появятся заметки.</div>';$('shoppingList').innerHTML=shops.length?shops.map(x=>itemMarkup(x,'shopping')).join(''):'<div class="empty-state">Список пока пуст.</div>';$('habitList').innerHTML=hs.length?hs.map(x=>itemMarkup(x,'habit')).join(''):'<div class="empty-state">Добавьте привычку — она появится на каждом дне.</div>';document.querySelectorAll('[data-item-check]').forEach(el=>el.addEventListener('change',async()=>{const x=item(el.dataset.itemCheck);if(x){x.data.done=el.checked;await persist()}}));document.querySelectorAll('[data-item-delete]').forEach(el=>el.addEventListener('click',async()=>{const x=item(el.dataset.itemDelete);if(x&&confirm('Удалить запись? Это изменение увидят все посетители календаря.'))await deleteRemote(x.id)}))}
  function itemMarkup(x,kind){const type=kind==='shopping'?'куплено':kind==='note'?'выполнено':'';return `<div class="item-row">${kind!=='habit'?`<input type="checkbox" aria-label="${type}" data-item-check="${escapeHtml(x.id)}" ${x.data.done?'checked':''}>`:''}<span class="item-text ${x.data.done?'done':''}">${escapeHtml(x.data.title||'')}</span><button type="button" class="delete-button" aria-label="Удалить" data-item-delete="${escapeHtml(x.id)}">×</button></div>`}
  function openDay(k){selectedDate=k;activeDay=k;$('dayModal').classList.remove('hidden');renderDay(k)}
  function renderDay(k){if(!item('unused')&&$('dayModal').classList.contains('hidden'))return;const tasks=allInstances(k),hs=habits(),rems=remindersFor(k);$('dayModalTitle').textContent=dateLabel(k);let html='<div class="day-details">';html+='<section class="detail-section"><h3>Задачи · '+tasks.length+'</h3>'+(tasks.map(t=>taskMarkup(t)).join('')||'<div class="empty-state">На этот день задач пока нет.</div>')+'</section>';if(rems.length)html+='<section class="detail-section"><h3>Напоминания</h3>'+rems.map(r=>`<div class="reminder-row"><div class="reminder-head"><strong>${escapeHtml(r.text)}</strong><span class="reminder-date">к ${dateLabel(r.eventDate,{day:'numeric',month:'short'})}</span></div></div>`).join('')+'</section>';if(hs.length)html+='<section class="detail-section"><h3>Ежедневные привычки</h3>'+hs.map(h=>`<label class="habit-detail"><input type="checkbox" data-habit="${escapeHtml(h.id)}" data-date="${k}" ${habitDone(h.id,k)?'checked':''}>${escapeHtml(h.data.title)}</label>`).join('')+'</section>';html+='</div>';$('dayDetails').innerHTML=html;$('dayDetails').querySelectorAll('[data-habit]').forEach(el=>el.addEventListener('change',async()=>{const id=`habit-check:${el.dataset.habit}:${el.dataset.date}`;if(el.checked)upsert(id,'habit_check',{habitId:el.dataset.habit,date:el.dataset.date});else remove(id);await persist()}));$('dayDetails').querySelectorAll('[data-task-done]').forEach(el=>el.addEventListener('change',async()=>{const t=allInstances(k).find(t=>t.taskId===el.dataset.taskDone);if(t)await setOccurrence(t,k,{done:el.checked})}));$('dayDetails').querySelectorAll('[data-edit-task]').forEach(el=>el.addEventListener('click',()=>{const t=allInstances(k).find(t=>t.taskId===el.dataset.editTask);if(t)openTaskForm(t,k)}));$('dayDetails').querySelectorAll('[data-delete-task]').forEach(el=>el.addEventListener('click',()=>deleteTaskOccurrence(el.dataset.deleteTask,k)));}
  function taskMarkup(t){const r=t.repeat||{},repeatText=r.type==='weekly'?' · повтор':r.type?.startsWith('monthly')?' · ежемесячно':'';return `<article class="event-row"><input type="checkbox" data-task-done="${escapeHtml(t.taskId)}" ${t.done?'checked':''} aria-label="Выполнено"><div class="event-main"><div class="event-title ${t.done?'done':''}">${t.time?`<span class="event-time">${escapeHtml(t.time)}</span> · `:''}${escapeHtml(t.title)}</div><div class="event-meta"><span>${escapeHtml(t.category||'Иное')}</span>${repeatText?`<span>${repeatText.slice(3)}</span>`:''}${t.reminderLead!=null?`<span>напоминание за ${Number(t.reminderLead)?`${t.reminderLead} дн.`:'день'}</span>`:''}</div>${t.description?`<div class="event-description">${escapeHtml(t.description)}</div>`:''}</div><div class="event-actions"><button class="small-action" data-edit-task="${escapeHtml(t.taskId)}">Изменить</button><button class="small-action remove" data-delete-task="${escapeHtml(t.taskId)}" aria-label="Удалить">×</button></div></article>`}
  async function setOccurrence(t,k,changes){const old=overrideRows(t.taskId,k)?.data||{taskId:t.taskId,date:k};upsert(`override:${t.taskId}:${k}`,'override',{...old,...changes});await persist()}
  async function deleteTaskOccurrence(id,k){const t=allInstances(k).find(x=>x.taskId===id);if(!t)return;let whole=false;if(t.series){const answer=prompt('Удалить только это событие или все будущие? Введите «одно» или «будущие». Прошлые записи сохранятся.','одно');if(answer===null)return;whole=/будущ/.test(answer.toLowerCase())}else if(!confirm('Удалить задачу? Изменение будет видно всем посетителям календаря.'))return;if(whole){const base=item(id);base.data.endDate=shift(k,-1);await persist()}else await setOccurrence(t,k,{cancelled:true})}
  function openTaskForm(task=null,date=selectedDate){editing=task?{task:clone(task),occurrenceDate:date}:null;$('taskModalTitle').textContent=task?'Изменить задачу':'Новая задача';$('taskId').value=task?.taskId||'';$('taskOccurrenceDate').value=task?date:'';$('taskTime').value=task?.time||'';$('taskTitle').value=task?.title||'';$('taskCategory').value=categoryNames.includes(task?.category)?task.category:'Работа';$('taskDescription').value=task?.description||'';$('taskDate').value=task?.date||date;$('repeatType').value=task?.repeat?.type||'none';$('repeatEnd').value=task?.endDate||'';$('reminderLead').value=task?.reminderLead==null?'':String(task.reminderLead);$('reminderText').value=task?.reminderText||'';$('monthlyDate').value=String(task?.repeat?.day||Number(($('taskDate').value||date).slice(-2)));$('monthlyOrdinal').value=String(task?.repeat?.ordinal||2);$('monthlyWeekday').value=String(task?.repeat?.weekday??6);document.querySelectorAll('#weekdayPicker input').forEach(x=>x.checked=(task?.repeat?.days||[]).includes(Number(x.value)));$('repeatOptions').open=Boolean(task?.repeat?.type&&task.repeat.type!=='none');syncRepeatFields();$('dayModal').classList.add('hidden');$('taskModal').classList.remove('hidden');setTimeout(()=>$('taskTime').focus(),30)}
  function syncRepeatFields(){const v=$('repeatType').value;$('weekdayPicker').classList.toggle('hidden',v!=='weekly');$('monthlyDateField').classList.toggle('hidden',v!=='monthly-date');$('monthlyWeekdayFields').classList.toggle('hidden',v!=='monthly-weekday');const has=v!=='none';$('reminderTextField').classList.toggle('hidden',!has||$('reminderLead').value==='')}
  function getRepeat(){const type=$('repeatType').value;if(type==='weekly')return {type,days:[...document.querySelectorAll('#weekdayPicker input:checked')].map(x=>Number(x.value))};if(type==='monthly-date')return {type,day:Number($('monthlyDate').value)};if(type==='monthly-weekday')return {type,ordinal:Number($('monthlyOrdinal').value),weekday:Number($('monthlyWeekday').value)};return {type:'none'}}
  async function saveTask(e){e.preventDefault();if(savingTask)return;savingTask=true;const button=$('taskForm').querySelector('button[type="submit"]');if(button)button.disabled=true;try{const time=$('taskTime').value.trim();if(time&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(time)){alert('Введите время в формате ЧЧ:ММ, например 09:30.');$('taskTime').focus();return}const repeat=getRepeat();if(repeat.type==='weekly'&&!repeat.days.length){alert('Выберите хотя бы один день недели.');return}const data={title:$('taskTitle').value.trim(),date:$('taskDate').value,time,category:$('taskCategory').value,description:$('taskDescription').value.trim(),repeat,endDate:$('repeatEnd').value||null};if($('reminderLead').value!==''){data.reminderLead=Number($('reminderLead').value);data.reminderText=$('reminderText').value.trim()}const oldId=$('taskId').value,occ=$('taskOccurrenceDate').value;let scope='all';if(oldId&&editing?.task.series){const ans=prompt('Сохранить изменения только для этого события или для всех будущих? Введите «одно» или «будущие». Прошедшие события останутся без изменений.','одно');if(ans===null)return;scope=/будущ/.test(ans.toLowerCase())?'future':'one'}if(oldId){const base=item(oldId);if(scope==='future'){base.data.endDate=shift(occ,-1);dirtyIds.add(oldId);const id=uid();upsert(id,'task',data)}else if(editing.task.series){const current=overrideRows(oldId,occ)?.data||{taskId:oldId,date:occ};upsert(`override:${oldId}:${occ}`,'override',{...current,fields:data})}else{upsert(oldId,'task',data)}}else upsert(uid(),'task',data);selectedDate=data.date;viewDate=fromKey(data.date);$('taskModal').classList.add('hidden');activeDay=data.date;await persist();openDay(data.date)}finally{savingTask=false;if(button)button.disabled=false}}
  function shiftPeriod(amount){if(view==='week')viewDate.setDate(viewDate.getDate()+7*amount);else viewDate.setMonth(viewDate.getMonth()+amount);renderCalendar()}
  $('previousPeriod').onclick=()=>shiftPeriod(-1);$('nextPeriod').onclick=()=>shiftPeriod(1);$('todayButton').onclick=()=>{viewDate=new Date();selectedDate=keyOf(viewDate);renderCalendar()};$('weekViewButton').onclick=()=>{view='week';$('weekViewButton').classList.add('selected');$('monthViewButton').classList.remove('selected');renderCalendar()};$('monthViewButton').onclick=()=>{view='month';$('monthViewButton').classList.add('selected');$('weekViewButton').classList.remove('selected');renderCalendar()};$('calendarContent').addEventListener('click',e=>{const b=e.target.closest('[data-month-day]');if(b){selectedDate=b.dataset.monthDay;viewDate=fromKey(selectedDate);openDay(selectedDate)}});$('addVisibleTaskButton').onclick=()=>openTaskForm(null,selectedDate);$('addDayTaskButton').onclick=()=>openTaskForm(null,activeDay||selectedDate);$('taskForm').addEventListener('submit',saveTask);$('repeatType').addEventListener('change',syncRepeatFields);$('reminderLead').addEventListener('change',syncRepeatFields);$('taskTime').addEventListener('input',e=>{const digits=e.target.value.replace(/\D/g,'').slice(0,4);e.target.value=digits.length>2?`${digits.slice(0,2)}:${digits.slice(2)}`:digits});
  function addSimple(form,input,kind){$(form).addEventListener('submit',async e=>{e.preventDefault();const text=$(input).value.trim();if(!text)return;const id=uid();upsert(id,kind,{title:text,done:false,created:new Date().toISOString()});$(input).value='';await persist()})}
  addSimple('noteForm','noteInput','note');addSimple('shoppingForm','shoppingInput','shopping');$('habitForm').addEventListener('submit',async e=>{e.preventDefault();const title=$('habitInput').value.trim();if(!title)return;upsert(uid(),'habit',{title,created:new Date().toISOString()});$('habitInput').value='';await persist()});
  document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).classList.add('hidden')));document.querySelectorAll('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target!==m)return;if(m.id==='cloudImportModal')$('cloudImportSkip').click();else m.classList.add('hidden')}));document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal-backdrop:not(.hidden)').forEach(m=>{if(m.id==='cloudImportModal')$('cloudImportSkip').click();else m.classList.add('hidden')})});
  async function migrateLegacy(){if(localStorage.getItem('my-rhythm-planner-migration-v2')==='done')return;let old;try{old=JSON.parse(localStorage.getItem(LEGACY_KEY))}catch{return}if(!old||(!old.tasks?.length&&!old.notes?.length))return;if(remote&&state.items.length)return;const notice=$('migrationNotice');$('migrationSummary').textContent=`В старом планере: ${old.tasks?.length||0} задач и ${old.notes?.length||0} заметок. Выберите импорт только после просмотра этих данных.`;notice.classList.remove('hidden');$('migrationSkip').onclick=()=>{localStorage.setItem('my-rhythm-planner-migration-v2','done');notice.classList.add('hidden')};$('migrationImport').onclick=async()=>{const preview=[...(old.tasks||[]).map(t=>`${t.date||''} ${t.time||''} ${t.title||''}`),...(old.notes||[]).map(n=>`Без даты: ${n.text||''}`)].slice(0,20).join('\n');if(!confirm(`Будут импортированы записи:\n\n${preview}\n\n${remote?'Они станут общими и публичными.':'Они останутся на этом устройстве.'}\n\nПродолжить?`))return;for(const t of old.tasks||[]){const id=uid();upsert(id,'task',{title:t.title||'Без названия',date:t.date||keyOf(new Date()),time:t.time||'',category:categoryNames.includes(t.category)?t.category:'Иное',description:t.description||'',repeat:{type:'none'},done:Boolean(t.done)})}for(const n of old.notes||[])upsert(uid(),'note',{title:n.text||'Заметка',done:Boolean(n.done),created:new Date().toISOString()});notice.classList.add('hidden');localStorage.setItem('my-rhythm-planner-migration-v2','done');await persist()}}
  async function init(){for(let n=1;n<=31;n++)$('monthlyDate').insertAdjacentHTML('beforeend',`<option value="${n}">${n}-е число</option>`);localLoad();const localSnapshot=clone(state.items);if(remote&&localSnapshot.length)localStorage.setItem(BACKUP_KEY,JSON.stringify(backupObject(localSnapshot)));render();if(remote){status('Подключаемся…','loading');try{await loadRemote();errorBanner('');status('Общий календарь синхронизирован');render();const marker=`my-rhythm-planner-cloud-import-v2:${encodeURIComponent(cfg.supabaseUrl)}`;if(!state.items.length&&localStorage.getItem(marker)!=='done'&&!sessionStorage.getItem(`${marker}:later`)){let backupItems=localSnapshot;try{if(!backupItems.length){const saved=JSON.parse(localStorage.getItem(BACKUP_KEY)||'null');if(saved)backupItems=parseBackup(JSON.stringify(saved))}}catch{backupItems=[]}await openCloudImport(backupItems)}await migrateLegacy();pollTimer=setInterval(async()=>{if(busy||dirtyIds.size||removedIds.size||document.hidden)return;try{await loadRemote();errorBanner('');status('Общий календарь синхронизирован');render()}catch(e){errorBanner(`Не удалось обновить общий календарь. Проверьте сеть или настройки базы. ${String(e.message||e).slice(0,100)}`)}},8000)}catch(e){errorBanner(`Не удалось загрузить общий календарь. Данные не отправлены. Проверьте подключение и настройки базы. Ошибка: ${String(e.message||e).slice(0,150)}`)}}else{status('Локально');await migrateLegacy()}}
  $('downloadBackupButton').addEventListener('click',()=>downloadBackup());
  function updateStartThumb(){const slider=$('startSlider'),thumb=$('startSliderThumb'),range=Number(slider.value);const maxLeft=Math.max(0,slider.clientWidth-thumb.offsetWidth-12);thumb.style.left=`${6+maxLeft*range/100}px`;slider.setAttribute('aria-valuetext',range>=95?'Отпустите, чтобы перейти в календарь':'Проведите стрелку вправо, чтобы перейти в календарь')}
  function applyScreen(){const isPlanner=location.hash.toLowerCase()==='#planner';$('homeScreen').classList.toggle('hidden',isPlanner);$('plannerScreen').classList.toggle('hidden',!isPlanner);document.body.classList.toggle('welcome-active',!isPlanner);if(isPlanner){render();$('startSlider').value='0';updateStartThumb()}else document.querySelectorAll('.modal-backdrop:not(#migrationNotice)').forEach(m=>m.classList.add('hidden'));window.scrollTo(0,0)}
  $('startSlider').addEventListener('input',updateStartThumb);$('startSlider').addEventListener('change',()=>{if(Number($('startSlider').value)>=95){location.hash='#planner'}else{$('startSlider').value='0';updateStartThumb()}});window.addEventListener('resize',updateStartThumb);
  window.addEventListener('hashchange',applyScreen);window.addEventListener('popstate',applyScreen);
  document.addEventListener('visibilitychange',async()=>{if(!document.hidden&&remote&&!busy&&!dirtyIds.size&&!removedIds.size){try{await loadRemote();errorBanner('');status('Общий календарь синхронизирован');render()}catch(e){errorBanner(`Не удалось обновить общий календарь. ${String(e.message||e).slice(0,120)}`)}}});
  init();applyScreen();
})();
